### ISSUE TITLE
3.0 Can't Select a City

### ISSUE THREAD

**Issue by QPFNAbch68** [Sparker0i/Weather#2]
When opening the app, we are prompted to enter a city. I entered my US city and the app indicated it was not in the database. I tried other cities including Chicago, New York and London - all failed to be recognized or in the database. Version 2+ had no difficulty finding my city. Thanks. Joe

**Comment by QPFNAbch68** [comment]
App downloaded from f-droid. All it shows is version 3.0. Version 3.0.1 doesn't seem to be available.

**Comment by Sparker0i** [comment]
Please be patient until 3.0.1 shows up in the FDroid store. Even I know it is not available yet. Their build bots might be having a lot of overload, due to which 3.0.1 might not be showing up yet. Please be patient.

There have been some internal changes due to which 3.0 is having that error. That bug has been fixed in 3.0.1.

Regards.
