### ISSUE TITLE
Indicator that the Location Was Succesfully Found Appears every single time the "Home" view is opened.

### ISSUE THREAD

**Issue by moriel5** [Sparker0i/Weather#35]
Every time the "Home" view is shown, not just the first time a location is added, there is an indicator showing that the location was found.
Is this supposed to be the intended behaviour?

Prerequisites:
The app needs to be already set up, i.e. after the introduction is completed.

Environment:
Device - Nexus 4
ROM - CRDroid
OS Version - 7.1.2

Steps to Reproduce:
1. Open the "Home" view, whether by opening the app, or by opening a different view within the app ("Weather Graphs", settings, etc.), and returning to the "Home" view.

If required, logs will be taken after I return from work.

**Comment by Sparker0i** [comment]
Hey there,

I did not get what you meant by location found indicator. AFAIK I haven't
written such a code in my app... If you do have screenshots of that please
attach them too

On 01-Feb-2018 12:41 PM, "moriel5" <notifications@github.com> wrote:

Every time the "Home" view is shown, not just the first time a location is
added, there is an indicator showing that the location was found.
Is this supposed to be the intended behaviour?

Prerequisites:
The app needs to be already set up, i.e. after the introduction is
completed.

Steps to recreate:

   1. Open the "Home" view, whether by opening the app, or by opening a
   different view within the app ("Weather Graphs", settings, etc.), and
   returning to the "Home" view.

If required, logs will be taken after I return from work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Sparker0i/Weather/issues/35>, or mute the thread

**Comment by moriel5** [comment]
I'll send you a screenshot when I'll be at work, I'm currently running late.

**Comment by moriel5** [comment]
I'm sorry about the delay, I hadn't had the chance to upload the screenshot earlier, in part due to the fact that my gallery's photo editor is incompatible with LOS 14.1 based ROMs.

Here is the screenshot, edited with Snapseed (hence I was unable to add a simple line around the icon):

 https://postimg.org/image/4n1k0o84r/

**Comment by Sparker0i** [comment]
Oh no, that is indeed how it is supposed to work. If I am able to retrieve
any data from the server, I get something to parse, hence the blue tick is
shown.

When you click on the home after coming back from graphs or maps, it asks
for new data from the server. That is how it is supposed to work for now.
I'll try improving this in future versions.

**Comment by moriel5** [comment]
Alright, thanks.
When I saw the "loading" borders around the circle, I thought to myself that it may be supposed to be like this.

I'm glad that this is the case.


By the way, have you heard of "Forecast"?
It's a closed-source weather app, that I am (ashamedly) using an old pirated version of, since I run a noGAPPS build, and unfortunately, due to some falsified legal issues, next to none of the weather apps (and services) get my location correct, or bring in accurate results (Google brings the proper information, however I am not going to use their online services if possible).

Forecast.io was one of the only services that brought proper support (OWM got worse after I had notified them about this a few years ago, and only since the last few weeks the situation has brightened up), and the only such service that had an app that was not bloated (Amber Weather used to be great, until it's company started bloating it).

To make a long story short, I think that it has a few features that could bring some inspiration.

**Comment by Sparker0i** [comment]
I'm unfortunately bound on the Weather provider issue. The main reason I chose OWM is that it provides me maximum number of calls per day (86400 calls). Other providers restrict it to 1000 calls per day. That is something I am wary of. I designed this app to be run by the end user. They would'nt really care about API keys and all that stuff. They will only see the app and the weather data.

For foreca (the backend Amber Weather uses), does not have a open way for developers to create an account

**Comment by moriel5** [comment]
Don't worry, you don't need to change anything to do with the weather provider, I was just explaining my situation.

I was simply offering to look at Forecast's features for the inspiration.
You don't have to pay to install it, just to use the Forecast.io provider (the dev had added OWM at a certain point).
